# Generated by Django 5.0.3 on 2024-03-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('mail', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
